-- MySQL Script generated by MySQL Workbench
-- Mon Jul  1 15:17:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Research_repository_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Research_repository_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Research_repository_database` DEFAULT CHARACTER SET utf8 ;
USE `Research_repository_database` ;

-- -----------------------------------------------------
-- Table `Research_repository_database`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research_repository_database`.`role` (
  `idrole` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(45) NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE INDEX `idrole_UNIQUE` (`idrole` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research_repository_database`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research_repository_database`.`institution` (
  `idinstitution` INT UNSIGNED NOT NULL,
  `institution_name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`idinstitution`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research_repository_database`.`researcher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research_repository_database`.`researcher` (
  `idresearcher` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `researcher_name` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `category_idcategory` INT UNSIGNED NOT NULL,
  `institution_idinstitution` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idresearcher`),
  INDEX `fk_researcher_institution1_idx` (`institution_idinstitution` ASC) VISIBLE,
  CONSTRAINT `fk_researcher_institution1`
    FOREIGN KEY (`institution_idinstitution`)
    REFERENCES `Research_repository_database`.`institution` (`idinstitution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research_repository_database`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research_repository_database`.`category` (
  `idcategory` INT UNSIGNED NOT NULL,
  `category_name` VARCHAR(45) NULL,
  `researcher_idresearcher` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcategory`),
  INDEX `fk_category_researcher1_idx` (`researcher_idresearcher` ASC) VISIBLE,
  CONSTRAINT `fk_category_researcher1`
    FOREIGN KEY (`researcher_idresearcher`)
    REFERENCES `Research_repository_database`.`researcher` (`idresearcher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research_repository_database`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research_repository_database`.`project` (
  `idproject` INT UNSIGNED NOT NULL,
  `project_title` VARCHAR(45) NULL,
  `case-study` VARCHAR(45) NULL,
  `category_idcategory` INT UNSIGNED NOT NULL,
  `category_idcategory1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproject`),
  INDEX `fk_project_category1_idx` (`category_idcategory1` ASC) VISIBLE,
  CONSTRAINT `fk_project_category1`
    FOREIGN KEY (`category_idcategory1`)
    REFERENCES `Research_repository_database`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research_repository_database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research_repository_database`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `date_of_birth` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` INT NULL,
  `role_idrole` INT UNSIGNED NOT NULL,
  `project_idproject` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iduser`, `role_idrole`, `project_idproject`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  INDEX `fk_user_role_idx` (`role_idrole` ASC) VISIBLE,
  INDEX `fk_user_project1_idx` (`project_idproject` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `Research_repository_database`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_project1`
    FOREIGN KEY (`project_idproject`)
    REFERENCES `Research_repository_database`.`project` (`idproject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Research_repository_database`.`supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Research_repository_database`.`supervisor` (
  `idsupervisor` INT NOT NULL,
  `supervisor_name` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `institution_idinstitution` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idsupervisor`, `institution_idinstitution`),
  INDEX `fk_supervisor_institution1_idx` (`institution_idinstitution` ASC) VISIBLE,
  CONSTRAINT `fk_supervisor_institution1`
    FOREIGN KEY (`institution_idinstitution`)
    REFERENCES `Research_repository_database`.`institution` (`idinstitution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
